title: Junchi Zhang's Homepage
page-top-title: Junchi Zhang
top-section-bg-text: Mathematics, Combinatorics
home-subtitle: Junchi Zhang 张俊驰
copyright-text: '&copy; Junchi Zhang 2025. All Rights Reserved.'
